# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e870071746cdeee108815fb6036bd40e82afc795829baf47137f474345dfdc046e1e2ebcf830be39832666af1eaa27fe716ce5f105781cb4a7024264a17c16fc

test:
  secret_key_base: 9437d384c3fc2fa5603856d2a1d570cb7a9cdd49ca0ae081f957df56c18f158cef92b26335f63b3554b0916c09a1ee1b5a6e52127dd08e7d0c388377638342e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
